### ISSUE TITLE
Add support for new GitHub feature

### ISSUE THREAD

**Issue by zer0Kerbal** [repository-settings/app#567]
`suggest updating pull request branches` is a recent addition. I skimmed probot's documentation, PR's and issues and didn't find it reference. 

thank you!

located under

* Settings
  * Pull Requests
    * Control how and when users are prompted to update their branches if there are new changes available in the base branch.
    * Whenever there are new changes available in the base branch, present an “update branch” option in the pull request.
      * [ ] Always suggest updating pull request branches

**Comment by foolioo** [comment]
[keep your pull request branch up-to-date](https://github.blog/changelog/2022-02-03-more-ways-to-keep-your-pull-request-branch-up-to-date/) (aka [Managing suggestions to update pull request branches](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-suggestions-to-update-pull-request-branches)) lacks of REST API which is utilized by ProBot Settings.

**Comment by svg153** [comment]
Probably, it works but it is not documented? -> https://github.com/google/go-github/pull/2313

I tested using `github-cli` in one of my repos, and it is working:

```
OR="myORG/myREPO"
gh api \
  --method PATCH \
  -H "Accept: application/vnd.github.v3+json" \
  /repos/"${OR}" \
  -F allow_update_branch=true
```

Except:

> Default to PR title for squash merge commits
> This will pre-populate the commit message with the PR title when performing a squash merge.

I see how the web UI works, and it is using the same URL (https://github.com/ORG/repos/settings/update_merge_settings) adding a new element `squash_pr_title` but I do not know the GitHub API id (I tested with `squash_pr_title` and `allow_squash_pr_title`, but do not work)

**Comment by gr2m** [comment]
The parameter is called `use_squash_pr_title_as_default` as per GitHub's OpenAPI spec

> Either `true` to allow squash-merge commits to use pull request title, or `false` to use commit message.

**Comment by svg153** [comment]
> The parameter is called `use_squash_pr_title_as_default` as per GitHub's OpenAPI spec
> 
> > Either `true` to allow squash-merge commits to use pull request title, or `false` to use commit message.

👌. Released in the last version of [octokit.js_v1.8.0](https://github.com/octokit/octokit.js/releases/tag/v1.8.0)

**Comment by dgokcin** [comment]
@gr2m I am referring to "Always suggest updating pull request branches" feature. I believe what you are talking about is something different.

**Comment by svg153** [comment]
> I'm not seeing a REST API parameter for that feature yet, sorry. I didn't check the GraphQL schema though, sometimes it has features that the REST API does not, and vice versa

Have you seen this [rest/repos/repos#update-a-repository](https://docs.github.com/en/rest/repos/repos#update-a-repository) ?

![image](https://user-images.githubusercontent.com/9192031/174994623-b01d58cf-0be5-4165-a603-3be7f02219df.png)

Other links:
* https://github.com/octokit/types.ts/blob/master/scripts/update-endpoints/generated/endpoints.json#L12868
* https://github.com/octokit/openapi/blob/0e636a10f9872a0ee0d633039e21ecef6b0caef2/generated/ghes-3.3-diff-to-ghes-3.4.json#L5432

**Comment by dgokcin** [comment]
@foolioo thanks. I can confirm that it is working with `allow_update_branch: true` under repository settings.

**Comment by taliastocks** [comment]
> @foolioo thanks. I can confirm that it is working with `allow_update_branch: true` under repository settings.

Should documentation be updated?

**Comment by travi** [comment]
> Should documentation be updated?

from the configuration example:

> repository:
>  # See https://docs.github.com/en/rest/reference/repos#update-a-repository for all available settings.

please feel free to suggest changes to make the idea more obvious, but all repo properties are supported in the settings file. it isnt realistic for us to keep them all listed in the example when the api docs already provide details

**Comment by dgokcin** [comment]
> > Should documentation be updated?
> 
> from the configuration example:
> 
> > repository:
> > # See https://docs.github.com/en/rest/reference/repos#update-a-repository for all available settings.
> 
> please feel free to suggest changes to make the idea more obvious, but all repo properties are supported in the settings file. it isnt realistic for us to keep them all listed in the example when the api docs already provide details

I agree that continuously updating the documentation about the features in the GitHub API is not a good idea, but I don't think many users of this action know that if a property is available in the GitHub API, it is supported by the Settings Bot. As a loyal user of this app for a few years now, I believe the main README deserves a mention of this in a more visible place, rather than a commented-out link.

**Comment by travi** [comment]
> deserves a mention of this in a more visible place, rather than a commented-out link

https://github.com/repository-settings/app/pull/893 pulls the reference to a more prominent location. closing this thread as a result of that change, but would entertain PRs to further improve the clarity of configuration docs
