### ISSUE TITLE
Support for Github Environments

### ISSUE THREAD

**Issue by niraj8** [repository-settings/app#607]
## Prerequisites:

* Is the functionality available in the GitHub UI? If so, please provide a link to information about the feature.
https://github.com/{org}/{repo}/settings/environments

* Is the functionality available through the GitHub API? If the functionality is available, please provide links to the
  API documentation (https://developer.github.com/v3/) as well as the Octokit documentation (https://octokit.github.io/).
-  https://docs.github.com/en/rest/deployments/environments

* If the functionality is not yet available in the API, it would be helpful if you
  contacted support (https://support.github.com/) or posted in the Community Forum (https://github.community/). Please
  include a link to the forum post if you create one or a copy of the response from support.

## New Feature

Please describe the desired new functionality:
Add support to manage Github environments with settings.yml

**Comment by niraj8** [comment]
@gr2m wdyt?

**Comment by celliott** [comment]
@gr2m do you have any thoughts on this issue? thx
