### ISSUE TITLE
releases

### ISSUE THREAD

**Issue by travi** [repository-settings/app#614]
#613 got me thinking a little bit about how what we consider this project to be. since probot apps can both be apps but also dependencies for other probot apps i'm a little conflicted on which way to treat this app as far as dependency pinning goes. i typically follow the renovate recommendation to pin all dependencies for apps, but leave definitions as ranges for libraries. 

we dont currently publish versioned releases, but we definitely have users running their own instances. @gr2m, you do a good job of handling releases for your probot apps, like https://github.com/wip/app/releases, so i'm curious about your thoughts on this. also, it feels a little odd to start versioning at v1.0.0 now since the app has been around for a while, but i don't have a better suggestion than that either 🤷🏼

**Comment by travi** [comment]
> I don't see a benefit in publishing an npm package for an app?

no, i agree. i wasnt clear with what i was referring to, partly because i think i've always been a little confused by it myself. i guess i was referring more to the idea of [Combining Apps](https://probot.github.io/docs/deployment/#combining-apps). In that situation, this "app" is less of an app and more of a dependency. 

for the common cases of our hosted deployment and others simply running their own instance as an independent app, i fully agree with treating the project as an app. semantic versioning makes less sense to me for projects that are only used as apps, though, since the semantic impact to the consumer really only matters if the project is used as a dependency. 

so, those are the ideas that i'm considering when trying to decide if it would be worth publishing releases that are semantically versioned, or approaching the communication of changes in a different way that better suits an app type project. since probot projects can sort of be both, i'm interested in your thoughts to consider how we could communicate changes more effectively.

**Comment by gr2m** [comment]
I have yet to run into a situation where I'd like to combine different probot apps into one. So I can't share much insights myself. Do you know of someone who imports the settings app as an npm package to combine it with others or to use it in their own?

When in doubt, I'd treat it as an "It's a problem when it's a problem" and not publish any npm package, until someone asks for it

**Comment by travi** [comment]
> Do you know of someone who imports the settings app as an npm package to combine it with others or to use it in their own?

we've seen requests come in to enable some of the functionality in library form, but i consider that as different than how the app is versioned.

> When in doubt, I'd treat it as an "It's a problem when it's a problem" and not publish any npm package, until someone asks for it

i agree about not publishing to npm. that wasnt really what i was thinking about anyway at this point. more just trying to think through whether _semantic_ versioning made sense if we decide to publish release notes or better communicate changes in some way. since i knew you used semantic-release for [wip releases](https://github.com/wip/app/blob/master/.github/workflows/release.yml), thats more the part i was curious about.

it sounds like we agree that we should focus on this project being an app rather than a dependency for others. i'm just not sure what to think about versioning if we improve our communication about changes.

**Comment by gr2m** [comment]
I'd say it's a breaking change when configuration format changes, or any other kinds of interactions with the app. If something used to work and stopps working, that's a breaking change.

**Comment by travi** [comment]
thats probably the perspective i wasnt considering. i was thinking more from the perspective of settings as a dependency, but config file compatibility is another interface that changes impact. no disagreement that the types of changes you mention are breaking. versioning for that interface makes sense to me. 

thanks for straightening out my thoughts 😄
