### ISSUE TITLE
Environments settings are not reflected.

### ISSUE THREAD

**Issue by kkasai** [repository-settings/app#702]
## Problem Description
Environments settings are not reflected.

### What is actually happening
I described the Environments settings with reference to README.md, but the settings are not reflected.
```
environments:
  - name: production
  - name: development
```

Is there anything wrong?

### What is the expected behavior
Environments settings should be reflected.

### Error output, if available
N/A

### Are you using the hosted instance of repository-settings/app or running your own?
hosted instance of repository-settings/app

### If running your own instance, are you using it with github.com or GitHub Enterprise?
github.com

#### Version of repository-settings/app
N/A

#### Version of GitHub Enterprise
N/A

**Comment by kkasai** [comment]
This page says that I need the authority of `actions:read` . Could you please put it on?
https://docs.github.com/ja/rest/deployments/environments?apiVersion=2022-11-28#get-an-environment

> Anyone with read access to the repository can use this endpoint. If the repository is private, you must use an access token with the repo scope. GitHub Apps must have the actions:read permission to use this endpoint.

**Comment by kkasai** [comment]
@travi 
I am sorry to bother you, but could you please check this?

**Comment by rlmartin** [comment]
@kkasai Is this on a personal private repo? If so, environments are not available for those repos (see the green box at the top of the [documentation](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment)). For environments to be available, the repo needs to either be public OR the repo needs to be on GitHub Pro, Team, or Enterprise. Furthermore, some environment features (such as approvers) are only available on Enterprise.

**Comment by kkasai** [comment]
@rlmartin 
> Is this on a personal private repo? 
No.

This is on a GitHub Enterprise.
I already use Environments, but I want to manage with `settings.yml` .

**Comment by travi** [comment]
i've added `actions:read` to the permissions requested by the hosted settings app

**Comment by travi** [comment]
i've also captured this need in the deployment doc for consumers. closing since i believe the need is covered, but please mention if you think there are other details that need attention.
