### ISSUE TITLE
Support for the auto-merge option

### ISSUE THREAD

**Issue by TueDissingWork** [repository-settings/app#742]
## Prerequisites:

* Is the functionality available in the GitHub UI? If so, please provide a link to information about the feature.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request

* Is the functionality available through the GitHub API? If the functionality is available, please provide links to the
  API documentation (https://developer.github.com/v3/) as well as the Octokit documentation (https://octokit.github.io/).

https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#update-a-repository

## New Feature

It would be great to see an option for controlling the `auto-merge` feature. It seems to be available via the API, but can't seem to find it in the settings (this app).

Also happy to give it a go on implementing this, but would love some pointers on how to approach this new feature -> where to start.

**Comment by ctoestreich** [comment]
The plugin config for `repository:` properties generally mapped as is so simply using `allow_auto_merge: true` should work:

```yaml
repository:
   name: xxxx
   #...other stuff
   allow_auto_merge: true
```

**Comment by TueDissingWork** [comment]
> The plugin config for `repository:` properties generally mapped as is so simply using `allow_auto_merge: true` should work:
> 
> ```yaml
> repository:
>    name: xxxx
>    #...other stuff
>    allow_auto_merge: true
> ```
> 
> In otherwords, settings from the root of the update repository are pass through as is https://docs.github.com/en/free-pro-team@latest/rest/repos/repos?apiVersion=2022-11-28#update-a-repository

Very nice. Will give it a try

**Comment by TueDissingWork** [comment]
Worked as expected
