### ISSUE TITLE
Verify Publisher

### ISSUE THREAD

**Issue by thetillhoff** [repository-settings/app#783]
## Prerequisites:

Information about the feature visibility in the Github UI:
https://docs.github.com/en/apps/publishing-apps-to-github-marketplace/github-marketplace-overview/about-marketplace-badges

## New Feature

As the repository-settings app is backed by vercel, it should be possible to get the publisher verified badge.
That would increase visibility and trust.
Trust is especially important, since the app basically gets admin permission on all repos it's installed into. Which is all repos of an organisation in an optimal world.
It could potentially do a lot of damage and having the publisher trusted would reduce the threshold of adoption.

**Comment by travi** [comment]
appreciate the suggestion @thetillhoff. however, we currently would not meet one of the requirements for verification. we do not have a project website at this point, and therefore do not have a domain. we are a very small maintenance team, so the extra maintenance of a project site is not something we are looking to add to our maintenance load. 

> As the repository-settings app is backed by vercel

I can understand the confusion here, but this project is not "backed by" vercel. instead, our hosted app has its hosting costs sponsored under thier [oss hosting program](https://vercel.com/guides/can-vercel-sponsor-my-open-source-project).

for orgs that do have project websites, i absolutely value pursuing validation, and do so where that is possible. i totally get your point, but verification simply doesnt make sense for us at this point. if the project grows at some point to the point where we can, we will. for now, you will have to make your own decision about how this impacts whether you use the project or not.
