### ISSUE TITLE
Typescript?

### ISSUE THREAD

**Issue by kristof-mattei** [repository-settings/app#999]
As I was debugging an issue with repository settings I started to look into the types exposed by GitHub and was wondering if the team would be interested in a TypeScript conversion of the source code.

I'd be happy to take the lead on it.

**Comment by travi** [comment]
We do not view typescript as something that would help us maintain the project, so we have no plan to give typescript priority over the many other things that need our attention with the project. We appreciate the offer though.

**Comment by kristof-mattei** [comment]
> We do not view typescript as something that would help us maintain the project, so we have no plan to give typescript priority over the many other things that need our attention with the project. We appreciate the offer though.

Sounds good. Thanks.
